import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateTuVi, calculateTimeline, compareChartFixture, sensitivity, compatibility, createGroundedPrompt, renderSvg, handleMcpMessage, validateInput, listVietnamCities, listMajorStars } from '../dist/index.js';
import { handleMcpMessage as handleMcpMessageFromSubpath } from '../dist/mcp/handler.js';
import { solarToVietnameseLunar } from '../dist/calendar.js';
test('calculates deterministic chart shape', () => {
  const input={localDateTime:'1990-05-17T14:30:00',timezoneOffsetMinutes:420,gender:'female',asOfYear:2026,asOfDate:'2026-07-26',include:{daiHan:true,tieuHan:true,luuNien:true,luuNguyet:true,luuNhat:true}};
  const a=calculateTuVi(input), b=calculateTuVi(input);
  assert.equal(a.palaces.length,12); assert.equal(a.stars.filter(s=>s.kind==='major').length,14);
  assert.deepEqual(a.palaces,b.palaces); assert.equal(a.timeline.daiHan.length,12);
  assert.equal(a.timeline.daiHan[0].palaceIndex,0);
  assert.equal(new Set(a.timeline.daiHan.map(x=>x.palaceIndex)).size,12);
  assert.ok(a.audit.some(x=>x.rule==='dai-han-direction'));
  assert.ok(a.audit.some(x=>x.rule==='luu-nien-year-branch'));
  assert.equal(a.timeline.tieuHan.nominalAge,37);
  assert.ok(a.audit.some(x=>x.rule==='tieu-han-position'));
  assert.equal(a.timeline.luuNguyet.asOfDate,'2026-07-26');
  assert.equal(a.timeline.luuNhat.asOfDate,'2026-07-26');
  assert.ok(a.audit.some(x=>x.rule==='luu-nguyet-dau-quan'));
  assert.ok(a.audit.some(x=>x.rule==='luu-nhat-lunar-day'));
  const preTet=calculateTuVi({...input,asOfDate:'2026-01-01'});
  assert.equal(preTet.audit.find(x=>x.rule==='luu-nien-year-branch').value,'Tỵ');
  assert.match(preTet.audit.find(x=>x.rule==='luu-nien-year-branch').source,/asOfDate/);
  assert.equal(preTet.timeline.tieuHan.nominalAge,36);
  assert.ok(a.audit.every(x=>typeof x.version==='string'&&x.version.length>0));
  const sensitive=sensitivity(input);
  assert.equal(sensitive.variants.length,3);
  assert.equal(sensitive.hourBranches.length,12);
  assert.ok(sensitive.stabilityScore>=0&&sensitive.stabilityScore<=1);
  const comparison=compatibility(input,input);
  assert.equal(typeof comparison.score,'number');
  assert.equal(comparison.aspects.length,2);
  assert.equal(comparison.aspects[0].relation,'same');
  assert.match(createGroundedPrompt(a).system, /bằng chứng/);
  const svg=renderSvg(a);
  assert.match(svg,/role="img"/);
  assert.match(svg,/viewBox="0 0 720 720"/);
  assert.match(svg,/Rule set vn-popular-0\.2/);
  assert.equal(handleMcpMessage({id:1,method:'capabilities'}).result.engine, 'viet-tuvi-engine');
  assert.equal(handleMcpMessage({id:2,method:'initialize'}).result.protocolVersion,'2025-06-18');
  assert.equal(handleMcpMessageFromSubpath({id:2,method:'initialize'}).result.protocolVersion,'2025-06-18');
  assert.equal(handleMcpMessage({id:14,method:'resources/list'}).result.resources.length,2);
  const resource=handleMcpMessage({id:15,method:'resources/read',params:{uri:'tuvi://methodology'}});
  assert.match(resource.result.contents[0].text,/vn-popular-0\.2/);
  assert.equal(handleMcpMessage({jsonrpc:'2.0',method:'notifications/initialized'}),null);
  const tools=handleMcpMessage({id:3,method:'tools/list'}).result.tools;
  assert.ok(tools.some(x=>x.name==='calculate'));
  const call=handleMcpMessage({id:4,method:'tools/call',params:{name:'calculate',arguments:input}});
  assert.equal(call.result.structuredContent.palaces.length,12);
  const utc = calculateTuVi({...input, timezoneOffsetMinutes: 0});
  const vn = calculateTuVi({...input, timezoneOffsetMinutes: 420});
  assert.notEqual(utc.audit.find(x=>x.rule==='year-can').value, undefined);
  assert.notEqual(utc.metadata.calculatedAt, vn.metadata.calculatedAt);
  const midnight=calculateTuVi({localDateTime:'2024-02-10T00:30:00',timezoneOffsetMinutes:420,gender:'male'});
  assert.equal(midnight.audit.find(x=>x.rule==='lunar-date').value,'2024-1-1');
  assert.equal(midnight.metadata.calculatedAt,'2024-02-09T17:30:00.000Z');
  assert.equal(midnight.palaces[0].branch,'Dần');
  assert.equal(midnight.palaces[0].isThan,true);
  const solar = calculateTuVi({...input,trueSolarTime:true,location:{city:'Hà Nội'}});
  assert.ok(solar.audit.some(x=>x.rule==='equation-of-time-minutes'));
  assert.ok(solar.audit.some(x=>x.rule==='true-solar-correction-minutes'));
  assert.deepEqual(solarToVietnameseLunar(10,2,2024,7), {day:1,month:1,year:2024,leap:false});
  assert.ok(a.audit.some(x=>x.rule==='menh-stem-branch'));
  assert.ok(a.audit.some(x=>x.rule==='cuc-na-yin-element'));
  assert.ok([2,3,4,5,6].includes(a.cuc.number));
  assert.equal(a.stars.filter(s=>s.kind==='auxiliary').length,49);
  assert.equal(a.stars.filter(s=>s.kind==='transformation').length, 4);
  assert.equal(a.stars.filter(s=>['trang-sinh','moc-duc','quan-doi','lam-quan','de-vuong','suy','benh','tu','mo','tuyet','thai','duong'].includes(s.code)).length,12);
  assert.equal(a.stars.filter(s=>s.code==='thai-tue').length,1);
  assert.equal(a.stars.filter(s=>s.code==='bac-si').length,1);
  for(const code of ['thien-khoi','thien-viet','thien-ma','dao-hoa','hong-loan','thien-hy']) assert.equal(a.stars.filter(s=>s.code===code).length,1);
  assert.ok(a.facts.every(f=>f.code&&f.text.vi&&f.text.en));
  assert.match(createGroundedPrompt(a,'en').evidence.palaces,/chart\.menh\.location/);
  const fallback=calculateTuVi({...input,tradition:'trung-chau'});
  assert.ok(fallback.warnings.some(x=>x.code==='tradition.baseline-fallback'));
  const missingLongitude=calculateTuVi({...input,trueSolarTime:true});
  assert.ok(missingLongitude.warnings.some(x=>x.code==='solar-time.longitude-missing'));
  assert.ok(createGroundedPrompt(fallback).evidence.warnings.length);
  const phiHoa=calculateTuVi({...input,include:{...input.include,phiHoa:true}});
  assert.equal(phiHoa.phiHoa.length,48);
  assert.equal(new Set(phiHoa.phiHoa.map(x=>x.code)).size,48);
  assert.ok(phiHoa.warnings.some(x=>x.code==='feature.phi-hoa-baseline'));
  assert.ok(phiHoa.audit.some(x=>x.rule==='phi-hoa-palace-stems'&&x.version==='palace-stem-phi-hoa-1'));
  assert.equal(handleMcpMessage({id:10,method:'capabilities'}).result.status.phiHoa,'baseline');
  assert.throws(()=>calculateTuVi({...input,localDateTime:'2024-02-30T12:00:00'}),/invalid calendar/);
  assert.throws(()=>calculateTuVi({...input,timezoneOffsetMinutes:900}),/timezoneOffsetMinutes/);
  assert.throws(()=>calculateTuVi({...input,asOfDate:'2026-02-30'}),/invalid calendar/);
  assert.equal(validateInput(input).valid,true);
  assert.equal(validateInput({...input,localDateTime:'bad'}).valid,false);
  const badLongitude=validateInput({...input,location:{longitude:181}});
  assert.equal(badLongitude.valid,false);
  assert.equal(badLongitude.issues[0].code,'input.location.longitude');
  assert.equal(validateInput({...input,trueSolarTime:'yes'}).valid,false);
  assert.equal(validateInput({...input,include:{unknown:true}}).valid,false);
  assert.equal(validateInput({...input,unknown:true}).valid,false);
  assert.equal(validateInput({...input,location:{city:'Hà Nội',latitude:21}}).valid,false);
  const validateCall=handleMcpMessage({id:5,method:'tools/call',params:{name:'validate-input',arguments:{...input,gender:'x'}}});
  assert.equal(validateCall.result.structuredContent.valid,false);
  const invalidMcp=handleMcpMessage({id:11,method:'calculate',params:{...input,timezoneOffsetMinutes:999}});
  assert.equal(invalidMcp.error.data.engineCode,'input.timezone-offset');
  assert.ok(listVietnamCities().length>=10);
  const cityCall=handleMcpMessage({id:6,method:'tools/call',params:{name:'cities',arguments:{}}});
  assert.equal(cityCall.result.structuredContent.cities[0].code,'vn-hanoi');
  const unaccented=calculateTuVi({...input,trueSolarTime:true,location:{city:'Da Nang'}});
  assert.notEqual(unaccented.audit.find(x=>x.rule==='longitude-correction-minutes').value,'0');
  const mismatchedZone=calculateTuVi({...input,timezoneOffsetMinutes:480,trueSolarTime:true,location:{city:'vn-hanoi'}});
  assert.ok(mismatchedZone.warnings.some(x=>x.code==='location.timezone-mismatch'));
  assert.match(mismatchedZone.audit.find(x=>x.rule==='longitude-correction-minutes').source,/120°/);
  const methodologyCall=handleMcpMessage({id:7,method:'tools/call',params:{name:'methodology',arguments:{}}});
  assert.equal(methodologyCall.result.structuredContent.ruleSetVersion,'vn-popular-0.2');
  assert.ok(methodologyCall.result.structuredContent.sources.some(x=>x.role==='comparison-oracle'));
  const svgCall=handleMcpMessage({id:8,method:'tools/call',params:{name:'render-svg',arguments:{chart:a}}});
  assert.match(svgCall.result.structuredContent.svg,/role="img"/);
  assert.equal(listMajorStars().length,14);
  assert.ok(a.stars.filter(s=>s.kind==='major').every(s=>s.element&&s.yinYang&&s.group));
  const catalogCall=handleMcpMessage({id:9,method:'tools/call',params:{name:'major-stars',arguments:{}}});
  assert.equal(catalogCall.result.structuredContent.stars.length,14);
  assert.equal(new Set(a.relations.map(x=>x.code)).size,a.relations.length);
  assert.ok(a.metadata.sources.some(x=>x.url.includes('tuvibacphai')));
  assert.equal(a.relations.filter(x=>x.type==='luc-hop').length,6);
  const timeline=calculateTimeline(input);
  assert.equal(timeline.timeline.daiHan.length,12);
  assert.ok(timeline.audit.every(x=>x.rule.includes('han')||x.rule.startsWith('luu-')));
  const timelineCall=handleMcpMessage({id:12,method:'tools/call',params:{name:'timeline',arguments:input}});
  assert.equal(timelineCall.result.structuredContent.timeline.tieuHan.nominalAge,37);
  const fixtureResult=compareChartFixture(input,{cuc:{code:a.cuc.code},palaces:[{index:0,branch:a.palaces[0].branch,isMenh:true,isThan:a.palaces[0].isThan}],stars:[{code:'tu-vi',palaceIndex:a.stars.find(x=>x.code==='tu-vi').palaceIndex}]});
  assert.equal(fixtureResult.match,true);
  const fixtureCall=handleMcpMessage({id:13,method:'tools/call',params:{name:'compare-fixture',arguments:{input,expected:{cuc:{code:a.cuc.code}}}}});
  assert.equal(fixtureCall.result.structuredContent.match,true);
});
